### ISSUE TITLE
How to Determine If PWA Install is From Windows Store?

### ISSUE THREAD

**Issue by bastecklein** [pwa-builder/pwabuilder-windows-chromium-docs#9]
I had a chromium-Edge based app built with PWA builder rejected from the Store because my site contains a link to other Web Apps that I develop on my own website, rather than links to the Windows Store, which they say violated their policy regarding linking to competing app stores.  I am wondering if there is a way in JS to determine if the site is running in the regular web browser, or if it was downloaded/installed through the Windows Store?  Is there a special global object or user agent line for apps installed from the store?

**Comment by marto55555** [comment]
I've noticed that recently Edge has started appending `?app-install-source=microsoft-store` to the launch URL of the PWA when it's installed from the Store.
I save this in `sessionStorage` so that it survives between page navigations:
```javascript
//On first page load:
if (new URL(location.href).searchParams.get('app-install-source') == 'microsoft-store') {
    sessionStorage.setItem('ms_store', 1);
}

//Later, when you need to check:
if (sessionStorage.getItem('ms_store')) {
    //PWA is installed from the MS Store
}
```

One issue: if your PWA defines app shortcuts or Share Target URLs, Edge doesn't seem to append `?app-install-source=microsoft-store` in those cases. If you launch your PWA from those ways, you can't detect if it was installed from the Store. Hopefully that'll be fixed soon.

**Comment by bastecklein** [comment]
Thank you @marto55555 that helps.  I will mark this as closed since it gets me what I am looking for!

**Comment by JudahGabriel** [comment]
@bastecklein and @marto55555,

Please be aware that the `app-install-source=microsoft-store` is a temporary measure. We (PWABuildder and the Microsoft Edge team) originally had intended this to be the permanent solution.

But Google raised some issues around service worker cache busting, as well as potential privacy issues.

In response to this feedback, we're deprecating the `app-install-source` query string. 

In place of this, when your Store PWA is launched, we'll set a `referrer` request header and set its value to `app-info://platform/microsoft-store`:

![image](https://user-images.githubusercontent.com/312936/124971203-c3c27680-dfdd-11eb-8162-25f5e405c555.png)

Note that this referrer header gets set only on app launch; successive navigations won't have that request header. 

This aligns with what Google is doing for PWAs from the Google Play Store. We're working with W3C to standardize this practice.

If you have any feedback about this direction, please let me know and I can relay it to the Edge and W3C groups.

**Comment by bastecklein** [comment]
Thank you for the update @JudahGabriel , I appreciate it.  Just to clarify, is this the regular referrer header that I can access in JS using document.referrer ?  So if an app is launched from the MS Store, document.referrer will = info://platform/microsoft-store ?

Anyway, thanks again for the update on this.

**Comment by JudahGabriel** [comment]
In my initial test, no, `document.referrer` is empty. This makes sense: `document.referrer` is meant to be empty if the page was loaded directly.

Instead, on your server, you'll inspect the _request headers_ and look for `referer`. If it equals `app-info://platform/microsoft-store`, then you know it was your Store PWA.

**Comment by marto55555** [comment]
Thanks for the response @JudahGabriel, but are you certain it's supposed to work like that? If I invoke the Store PWA from a Share target, `document.referrer` is set to `app-info://platform/microsoft-store`, just like the request header server-side. The current behavior of Edge also differs from Android Chrome, where a Play Store PWA (trusted web activity) always sets the `document.referrer` even if launched from the app icon. The `Referer` request header is also set to the same value.

I'm asking because I use Cloudflare CDN caching for my PWA and I cannot easily modify the server response based on the `Referer` header without causing unintended consequences. Therefore, it would be great if I can continue using JS to show/hide the Store-specific stuff in my PWA.

**Comment by JudahGabriel** [comment]
> are you certain it's supposed to work like that?

I'm testing it on my machine, and that's how it's working. Yeah. If you're saying, "Hey, I want document.referrer to be set as well", I can give that feedback to the Edge team.

> I'm asking because I use Cloudflare CDN caching for my PWA and I cannot easily modify the server response based on the Referer header without causing unintended consequences. 

I don't follow here.

The general idea would be: your server gets a request, it sees that the `Referer` header is set, and so you set a flag on the session indicating it was launched from the Store. You can even pass that info down to the client and access that flag via JS.

Am I missing something?

**Comment by marto55555** [comment]
@JudahGabriel 

> If you're saying, "Hey, I want document.referrer to be set as well", I can give that feedback to the Edge team.

Yes, that’s what I need. Thank you for checking this with the Edge team.

> Am I missing something? Are you thinking Cloudflare would break that behavior? We see that Cloudflare passes request headers through to the origin site, so I think this scenario should still work for you.

Sorry, I did a poor job trying to explain it.

I meant that I have set up a Cloudflare Page rule to “Cache Everything,” which includes `text/html` resources. The homepage (which is also the PWA’s `start_url`) has this Page rule applied to it. The problem is that if I change the HTML response server-side based on the `Referer` header (e.g. to remove some buttons shown only in the MS Store PWA version), other non-Store-PWA users who are also served from the same Cloudflare cache will still see those buttons.

This is why I currently serve an identical version to all users, and then hide/show the buttons in JS, based on the values of `url.searchParams.get('app-install-source')` and `document.referrer`. (I’ll remove the `searchParams` check when it’s no longer needed in the future.)

**Comment by JudahGabriel** [comment]
If `document.referrer` works as you expect, then this whole solution will work for you, yeah?  Cloudflare's caching wouldn't break that? You could still do JS-side UI updates based on that.

**Comment by marto55555** [comment]
@JudahGabriel 

> If document.referrer works as you expect, then this whole solution will work for you, yeah? Cloudflare's caching wouldn't break that? You could still do UI updates from JS based on that.

Yes, that is correct.

**Comment by JudahGabriel** [comment]
Cool. I'll tell the Edge team this client-side scenario is very important for some developers. And I'll tell them `document.referrer` will fill this need, but that it's not currently working today.
